version: "3.9"

services:
  mariadb:
    build: ./mariadb/ #build from this directory
    restart: unless-stopped
    volumes: 
      - volume-mariadb:/var/lib/mysql #use this volume
    environment:
      - MARIADB_ROOT_PASSWORD=secure_password;

  # wordpress:
  #   build: ./wordpress/
  #   volume: volume-wordpress:/var/lib/wordpress
  #   restart: unless-stopped

  # nginx:
  #   build: ./nginx/
  #   volume: volume-wordpress:/var/lib/wordpress:ro #make volume readonly, idk if i should do this
  #   restart: unless-stopped


volumes:
  volume-mariadb:
    driver_opts: #this is needed to mount names volumes, nowhere does it explain why it needs to be like this but ok
      type: none
      o: bind
      device: ${HOME}/data/mariadb

  # volume-wordpress:    
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ${HOME}/data/wordpress