version: "3.9"

networks:
  frontend:

services:
  mariadb:
    container_name: mariadb 
    build: ./mariadb/ #build from this directory
    restart: unless-stopped 
    volumes: 
      - volume-mariadb:/var/lib/mysql #use this volume
    networks:
      - frontend  #networks it can be found on
    expose:
      - 3306 #ports exposed to other containers

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb  #needs this to be running to run itself
    build: ./wordpress/
    volumes: 
      - volume-wordpress:/var/www/html
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=reguser
      - WORDPRESS_DB_PASSWORD=regpassword
      - WORDPRESS_ADMIN=notuser
      - WORDPRESS_ADMIN_PASS=notpassword
      - WORDPRESS_USER_PASS=password
    ports:
      - 9000:9000
    networks:
      - frontend

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./nginx/
    ports:
      - 80:80   #map port 80 on local machine to port 80 in container
      - 443:443
    volumes: 
    - volume-wordpress:/var/www/html
    restart: unless-stopped
    networks:
      - frontend


volumes:
  volume-mariadb:
    driver_opts: #this is needed to mount named volumes, nowhere does it explain why it needs to be like this but ok
      type: none
      o: bind
      device: ${HOME}/data/mariadb    #this volume is saved in /data/mariadb in the home directory

  volume-wordpress:    
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress