version: "3.9"

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb/ #build from this directory
    restart: unless-stopped
    volumes: 
      - volume-mariadb:/var/lib/mysql #use this volume
    environment:
      - MARIADB_ROOT_PASSWORD=secure_password;
    networks:
      - frontend

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./wordpress/
    volumes: 
      - volume-wordpress:/var/lib/wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=password
    networks:
      - frontend

  # nginx:
  #   container_name: nginx
  #   depends_on:
  #     - wordpress
  #   build: ./nginx/
  #   volumes: 
  #   - volume-wordpress:/var/lib/wordpress:ro #make volume readonly, idk if i should do this
  #   restart: unless-stopped
  #   networks:
  #     - frontend

networks:
  frontend:

volumes:
  volume-mariadb:
    driver_opts: #this is needed to mount names volumes, nowhere does it explain why it needs to be like this but ok
      type: none
      o: bind
      device: ${HOME}/data/mariadb

  volume-wordpress:    
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress