version: "3.9"

networks:
  frontend:

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb/ #build from this directory
    restart: unless-stopped
    volumes: 
      - volume-mariadb:/var/lib/mysql #use this volume
    environment:
      - MARIADB_ROOT_PASSWORD=secure_password;
    networks:
      - frontend
    expose:
      - 3306

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./wordpress/
    volumes: 
      - volume-wordpress:/var/lib/wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=reguser
      - WORDPRESS_DB_PASSWORD=regpassword
    networks:
      - frontend

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./nginx/
    ports:
      - 8080:80
    volumes: 
    - volume-wordpress:/var/lib/wordpress
    restart: unless-stopped
    networks:
      - frontend


volumes:
  volume-mariadb:
    driver_opts: #this is needed to mount names volumes, nowhere does it explain why it needs to be like this but ok
      type: none
      o: bind
      device: ${HOME}/data/mariadb

  volume-wordpress:    
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress