FROM debian:buster

RUN apt-get update && apt-get install --no-install-recommends -y \
    nginx \
    openssl

# get ssl cert
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/nginx-ssl.key -out /etc/ssl/nginx-ssl.crt -subj '/CN=localhost'
RUN mkdir -p /run/nginx && chmod -R 777 /var/www/html

#copy necessary files
COPY nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www/html

#startup nginx
ENTRYPOINT ["nginx", "-g", "daemon off;"]


