FROM debian:buster

RUN apt-get update && apt-get install --no-install-recommends -y \
    nginx

RUN mkdir -p /run/nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]