FROM debian:buster

#apt update and install the dependencies we need
RUN apt-get update && apt-get install -y \
    php-fpm \
    php-mysql \
    mariadb-client \
    wget

#install wp-cli and set it up
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

WORKDIR /var/www/html/wordpress

#copy setup script into container and run it
COPY conf.sh /tmp/configure.sh
ENTRYPOINT [ "sh", "/tmp/configure.sh" ]
