FROM debian:buster

#apt update and install the dependencies we need
RUN apt-get update && apt-get install --no-install-recommends -y \
    php-fpm \
    php-mysql \
    mariadb-client \
    wget \
    ca-certificates

#install wp-cli and set it up
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

RUN mkdir -p /run/php

COPY php-fpm.conf /etc/php/7.3/php-fpm.conf
COPY www.conf /etc/php/7.3/fpm/pool.d/www.conf

WORKDIR /var/www/html/wordpress

#copy setup script into container and run it
COPY conf.sh /tmp/configure.sh
# CMD [ "sleep", "infinity" ]
ENTRYPOINT [ "sh", "/tmp/configure.sh" ]
